[package]
name = "gandalfd"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
hickory-resolver = "0.26.1"
hickory-server = "0.26.1"
reqwest = { version = "0.13.4", features = ["rustls"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }

[dev-dependencies]
tempfile = "3.27.0"
